### PR TITLE
Use ES6 style export, don't reuse THREE namespace

### PR DESCRIPTION
**Pull request by timraasveld**
Importing this awesome project in a ES6+webpack project is problematic, the section:
```javascript
if(typeof module == 'undefined')
  var module = {};

if(typeof require == 'undefined')
    var require = function(){return undefined;};
```
causes the method `require` to be redefined when the module is loaded, even though `window.require` actually exists by the time the module is actually used. This causes THREE to be undefined by the time `THREE.MapControls = function () { ...` is executed.

By using ES6 exports and specifying a `prepublish` command to transpile to ES5 in `package.json`, I believe the project will be usable for both ES5 and ES6 projects with the generated import/export boilerplate. But please take this statement with a grain of salt, I'm quite new to npm packaging.

### CODE REVIEW

**Comment by sikanrong** [comment]
Hey man, thank you so much for your contribution!! I'll review this PR and your other one tomorrow or the next day and get things merged in. I really appreciate this. Just wanted to say thanks. 

One thing that kinda sucks is that you're using an editor that double-spaces things (I think?) or maybe it just changes my spacing. In any case, if you look at the PR the merge modifies every line, which is undesirable. Maybe you can re-make the PR without mangling the spacing as such, and then I can merge in your changes, which will give you the right attribution in the project.

**Comment by timraasveld** [comment]
> Hey man, thank you so much for your contribution!! I'll review this PR and your other one tomorrow or the next day and get things merged in. I really appreciate this. Just wanted to say thanks.

You're welcome, I desperately needed Google Maps-like controls for my project and was so happy to find your work. Least I can do back 😃 

> One thing that kinda sucks is that you're using an editor that double-spaces things (I think?) or maybe it just changes my spacing. In any case, if you look at the PR the merge modifies every line, which is undesirable. Maybe you can re-make the PR without mangling the spacing as such, and then I can merge in your changes, which will give you the right attribution in the project.

Didn't notice you used four spaces of indentation, sorry! Also, I temporarily added some extra indentation to the main implementation so it will show up on the diff. We just have to revert https://github.com/sikanrong/three-map-controls/pull/2/commits/42436aa50fc4485bfd2ccf24bc1289a4bde309ce before merge to use four spaces again.

**Comment by sikanrong** [comment]
Hey @timraasveld, finally today I managed to merge in your changes! Sorry for the delay, I just needed to find the time to really test your code and assess exactly what was changed, etc. So I merged in your pull-requests, made a few small changes to my own stuff, and released version 0.11.4 of the package. I guess you can now safely adjust your package.json file(s) to reflect that. Thanks again for the help, I really like the use of ES6 + babelify as a better deployment strategy. I promise future PRs will be merged much faster; I've just been really busy with my other code-projects.

I added browserify to the project so that I can keep a fully packaged bundle in dist which I use for jsfiddle demos (via the rawgit.com CDN) and the demo included in the repo index.html...

**Comment by timraasveld** [comment]
Awesome, thanks, also for fixing the build!

**Pull request merged**
